### ISSUE TITLE
Dependencies broken

### ISSUE THREAD

**Issue by jmunozdev** [rezakhademix/laravel-docker#7]
Some dependencies are broken when following the readme installation instructions, first of all i'm getting `Package 'oniguruma', required by 'virtual:world', not found`, fixing it by [removing the mbstring dependency](https://stackoverflow.com/questions/59251008/docker-laravel-configure-error-package-requirements-oniguruma-were-not-m) i'm getting another new error `Package 'libcurl', required by 'virtual:world', not found`

**Comment by rezakhademix** [comment]
Hi...
Thank you for letting me know, so here is the new deal:
From I don't know when,  php `mbstring` needs oniguruma-dev package to properly work! 
I fixed the mentioned issues and upgraded php version to `8.1` and it is okay now.

**Comment by jmunozdev** [comment]
Great! thank you!
